version: "3.9"


services:

  redis:
    image: redis:7
    container_name: ims-redis
    ports:
      - "6379:6379"
    networks:
      - ims_network

  mongo:
    image: mongo:6
    container_name: ims-mongo
    ports:
      - "27017:27017"
    networks:
      - ims_network

  backend:
    build:
      context: ./backend
    container_name: ims-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    networks:
      - ims_network

  worker:
    build:
      context: ./backend
    container_name: ims-worker
    working_dir: /app
    command: ["python", "-u", "app/workers/worker.py"]
    depends_on:
      - redis
      - mongo
    networks:
      - ims_network

  frontend:
    build:
      context: ./frontend
    container_name: ims-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - ims_network

networks:
  ims_network:
